### PR TITLE
fix the list max_results bug

### LINKED ISSUE #261: max_results doesn't set for list command in CLI
**Describe the bug**
The "max_results" param doesn't get set for the list commands in CLI. It is [hardcoded to 100](https://github.com/unitycatalog/unitycatalog/blob/2e6962e20129cc5b62432634fbbcdab88111db5e/examples/cli/src/main/java/io/unitycatalog/cli/TableCli.java#L142).

**To Reproduce**

1. bin/start-uc-server
2. bin/uc table list --catalog unity --schema default --max_results 2

This will return all the tables.

**Expected behavior**
It should return the tables as per the number passed to the max_results parameter.

**System [please complete the following information]:**

-   OS: macOS Sonoma 14.5

**Additional context**
The same thing is hardcoded for all the other list commands. 
- [catalog](https://github.com/unitycatalog/unitycatalog/blob/2e6962e20129cc5b62432634fbbcdab88111db5e/examples/cli/src/main/java/io/unitycatalog/cli/CatalogCli.java#L64)
- [function](https://github.com/unitycatalog/unitycatalog/blob/2e6962e20129cc5b62432634fbbcdab88111db5e/examples/cli/src/main/java/io/unitycatalog/cli/FunctionCli.java#L101)
- [schema](https://github.com/unitycatalog/unitycatalog/blob/2e6962e20129cc5b62432634fbbcdab88111db5e/examples/cli/src/main/java/io/unitycatalog/cli/SchemaCli.java#L63)
- [volume](https://github.com/unitycatalog/unitycatalog/blob/2e6962e20129cc5b62432634fbbcdab88111db5e/examples/cli/src/main/java/io/unitycatalog/cli/VolumeCli.java#L82)

### PR DESCRIPTION
**Pull request by vksx**
**PR Checklist**

* [x] A description of the changes is added to the description of this PR.
* [x] If there is a related issue, make sure it is linked to this PR.
* [ ] If you've fixed a bug or added code that should be tested, add tests!
* [ ] If you've added or modified a feature, documentation in `docs` is updated

**Description of changes**
Bugfix for "max_results" while listing assets.

Let me know if this works - I'll make similar changes to the other levels (catalog, schema, function, volume) as well.

Fixes #261

### CODE REVIEW

**Review by vikrantpuppala — APPROVED** [review]
lgtm, thanks for making this change @vksx.
@haogang could we merge please?

File: examples/cli/src/main/java/io/unitycatalog/cli/TableCli.java [hunk 1]
```diff
@@ -134,12 +134,16 @@ private static void handleTableStorageLocation(
 
   private static String listTables(TablesApi tablesApi, JSONObject json)
       throws JsonProcessingException, ApiException {
+    int maxResults = 100;
```
Comment (vikrantpuppala) [inline examples/cli/src/main/java/io/unitycatalog/cli/TableCli.java:137]: nit: 100 could be constant somewhere that we use across entities?

**Review by haogang — APPROVED** [review]

**Comment by vksx** [comment]
@vikrantpuppala Sorry if this is a beginner question - but should I create a separate PR for the other assets (catalog, schema, function, volume)? Currently, this PR only resolved the "max_results" issue for listing tables.
