### PR TITLE
Iceberg REST Service: Throw 400 if namespace is invalid

### LINKED ISSUE #10: Can't list tables from pyiceberg
Hey! Tried to see if I could query the default tables from pyiceberg, but I couldn't get further than listing namespaces (which does work), any ideas?

```python
from pyiceberg.catalog import load_catalog

catalog = load_catalog('default', **{
    'uri': 'http://127.0.0.1:8080/api/2.1/unity-catalog/iceberg',
})

print(catalog.list_namespaces())

print(catalog.list_tables(namespace='unity'))
```

results in 

```
[('unity',)]

Traceback (most recent call last):
  File "python3.11/site-packages/pyiceberg/catalog/rest.py", line 513, in list_tables
    response.raise_for_status()
  File "python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://127.0.0.1:8080/api/2.1/unity-catalog/iceberg/v1/namespaces/unity/tables

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "unitycatalog-dev/main.py", line 9, in <module>
    print(catalog.list_tables(namespace='unity'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "unitycatalog-dev/.venv/lib/python3.11/site-packages/pyiceberg/catalog/rest.py", line 515, in list_tables
    self._handle_non_200_response(exc, {404: NoSuchNamespaceError})
  File "unitycatalog-dev/.venv/lib/python3.11/site-packages/pyiceberg/catalog/rest.py", line 382, in _handle_non_200_response
    raise exception(response) from exc
pyiceberg.exceptions.ServerError: RESTError 500: Received unexpected JSON Payload: {"error_code":"INTERNAL","details":[{"reason":"INTERNAL","metadata":{},"@type":"google.rpc.ErrorInfo"}],"stack_trace":"[io.unitycatalog.server.service.IcebergRestCatalogService.listTables(IcebergRestCatalogService.java:210), com.linecorp.armeria.internal.server.annotation.AnnotatedService.invoke(AnnotatedService.java:382), com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve0(AnnotatedService.java:298), com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve(AnnotatedService.java:272), com.linecorp.armeria.internal.server.annotation.AnnotatedService.serve(AnnotatedService.java:78), com.linecorp.armeria.internal.server.annotation.AnnotatedService$ExceptionHandlingHttpService.serve(AnnotatedService.java:536), com.linecorp.armeria.server.HttpServerHandler.serve0(HttpServerHandler.java:463), com.linecorp.armeria.server.HttpServerHandler.handleRequest(HttpServerHandler.java:398), com.linecorp.armeria.server.HttpServerHandler.channelRead(HttpServerHandler.java:281), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412), com.linecorp.armeria.server.Http1RequestDecoder.channelRead(Http1RequestDecoder.java:282), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412), com.linecorp.armeria.server.HttpServerUpgradeHandler.channelRead(HttpServerUpgradeHandler.java:227), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412), io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436), io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346), io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318), io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412), io.netty.handler.logging.LoggingHandler.channelRead(LoggingHandler.java:280), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412), io.netty.handler.flush.FlushConsolidationHandler.channelRead(FlushConsolidationHandler.java:152), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412), io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440), io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420), io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919), io.netty.channel.kqueue.AbstractKQueueStreamChannel$KQueueStreamUnsafe.readReady(AbstractKQueueStreamChannel.java:544), io.netty.channel.kqueue.AbstractKQueueChannel$AbstractKQueueUnsafe.readReady(AbstractKQueueChannel.java:387), io.netty.channel.kqueue.KQueueEventLoop.processReady(KQueueEventLoop.java:218), io.netty.channel.kqueue.KQueueEventLoop.run(KQueueEventLoop.java:296), io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997), io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74), io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30), java.base/java.lang.Thread.run(Thread.java:840)]","message":"invalid namespace unity"}, errors: Field required

Process finished with exit code 1
```

### PR DESCRIPTION
**Pull request by amogh-jahagirdar**
Fixes #10 to have the right behavior of a 400 when failing.

Currently, an IllegalArgumentException for invalid namespace will be thrown which will end up surfacing as a 500 response due to https://github.com/unitycatalog/unitycatalog/blob/main/server/src/main/java/io/unitycatalog/server/exception/GlobalExceptionHandler.java#L26 treating this as an arbitrary runtime exception. Instead a Base exception with an invalid argument error code should be thrown (looking at other parts of the code, this seems to be the practice).

### CODE REVIEW

File: server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java [hunk 1]
```diff
@@ -171,7 +171,7 @@ public LoadTableResponse loadTable(@Param("namespace") String namespace,
                                      @Param("table") String table) throws IOException {
     List<String> namespaceParts = Splitter.on(".").splitToList(namespace);
     if (namespaceParts.size() != 2) {
-      throw new IllegalArgumentException("invalid namespace " + namespace);
+      throw new BaseException(ErrorCode.INVALID_ARGUMENT, "invalid namespace " + namespace);
```
Comment (amogh-jahagirdar) [inline server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java:174]: Working on tests.

Also just realized, for this to be spec compliant we should make sure errors get surfaced with the IcebergErrorResponse https://github.com/apache/iceberg/blob/main/open-api/rest-catalog-open-api.yaml#L3197

Comment (tdas) [reply server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java:174]: Thank you for catching this!

**Review by tdas — CHANGES_REQUESTED** [review]
Will merge when there are tests

File: server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java (hunk 1 above)
Comment (amogh-jahagirdar) [reply server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java:174]: Added tests, I've created a separate issue [here](https://github.com/unitycatalog/unitycatalog/issues/46) so we can track effort to make all the error responses spec compliant. Seemed easier for review if we tackle that separately since it touches more parts.

**Comment by dennyglee** [comment]
Thanks @amogh-jahagirdar, this looks great!  @tdas @rameshchandra could you also review to make sure I didn't miss anything?

File: server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java [hunk 2]
```diff
@@ -149,7 +149,7 @@ public HttpResponse tableExists(@Param("namespace") String namespace,
                                   @Param("table") String table) {
     List<String> namespaceParts = Splitter.on(".").splitToList(namespace);
     if (namespaceParts.size() != 2) {
-      throw new IllegalArgumentException("invalid namespace " + namespace);
+      throw new BaseException(ErrorCode.INVALID_ARGUMENT, "invalid namespace " + namespace);
     }
```
Comment (rameshchandra) [inline server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java:153]: Nit: suggest refactoring this repeated code into a separate method like the following:

```
  private List<String> splitTwoPartNamespace(String namespace) {
    List<String> namespaceParts = Splitter.on(".").splitToList(namespace);
    if (namespaceParts.size() != 2) {
      String errMsg = "Invalid two-part namespace " + namespace;
      throw new BaseException(ErrorCode.INVALID_ARGUMENT, errMsg);
    }

    return namespaceParts;
  }
```

Comment (amoghjaha-db) [reply server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java:153]: Good suggestion! will update

Comment (amogh-jahagirdar) [reply server/src/main/java/io/unitycatalog/server/service/IcebergRestCatalogService.java:153]: Good suggestion! Will update

**Review by rameshchandra — APPROVED** [review]
